---

- name: Update apt
  apt:
    update_cache: yes

- name: Install IRIDA dependencies
  apt:
    name:
      - openjdk-11-jdk
      - tomcat9
      - libtcnative-1
      - mariadb-server
      - python3-mysqldb
      - fastqc
    state: present

# Create IRIDA file trees and create config files
- include_tasks: irida_files.yml

# Grant privileges and create database
- include_tasks: irida_database.yml

- name: Set environment variables for tomcat9 Servlet container
  template:
    dest: "{{ tomcat_conf_file }}"
    src: tomcat9.j2

- name: Set environment variables for tomcat9 in setenv.sh
  template:
    dest: /usr/share/tomcat9/bin/setenv.sh
    src: setenv.sh

- name: Edit server.xml file for tomcat9
  template:
    dest: /etc/tomcat9/server.xml
    src: server.xml.j2

- name: Restart tomcat9
  service:
    name: tomcat9
    state: restarted
    enabled: yes

- name: Download IRIDA .war file
  get_url:
    url: "{{ irida_war_url }}"
    dest: "{{ tomcat_webapps }}/irida.war"
    owner: tomcat
    group: tomcat

- include_tasks: nginx.yml

- include_tasks: wait_irida_web.yml
