---

- name: Create IRIDA file tree
  file:
    path: "{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
  with_items:
    #- "{{ irida_dir }}"
    - "{{ irida_data }}"
    - "{{ irida_sequencing }}"
    - "{{ irida_reference }}"
    - "{{ irida_analysis }}"
    - "{{ irida_snapshot }}"
    - "{{ irida_assembly }}" 
    - "{{ irida_snapshot }}"

- name: Create tomcat9 service directory
  file:
    path: "{{ tomcat_service_d }}"
    state: directory

- name: Create /etc/irida file tree
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ irida_conf_dir }}"
    - "{{ irida_analytics }}"

- name: Copy override.conf for tomcat9 service directory
  template:
    dest: "{{ tomcat_service_d }}/override.conf"
    src: override.conf.j2

- name: Edit irida.conf and web.conf files
  template:
    dest: "{{ irida_conf_dir }}/web.conf"
    src: web.conf.j2

- name: Read irida_api_key from ini file
  shell:
    cmd: "awk -F '=' '/irida_api_key/ {print $2}' {{ irida_dir }}/irida_galaxy_user.ini | tr -d ' '"
  register: ini_parsing

- name: Set irida_api_key variable
  set_fact:
    irida_api_key: "{{ ini_parsing.stdout }}"

- name: Edit irida.conf file
  template:
    dest: "{{ irida_conf_dir }}/irida.conf"
    src: irida.conf.j2
